version: '3'
services:
  webserver:
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./htdocs:/var/www/html:ro
      - ./assets/:/etc/nginx/assets/:ro
    image: treetips/simple-static-file-viewer
    container_name: simple-static-file-viewer
    tty: true
    restart: always
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    ports:
      - "8081:80"
    command: "nginx -g 'daemon off;'"
